# Run tests manually workflow:
# This workflow allows manual execution of tests using the "workflow_dispatch" event.
# It performs the following actions:
# 1. Checks out the repository code.
# 2. Sets up the Node.js environment.
# 3. Caches Node.js dependencies to speed up subsequent runs.
# 4. Configures logs-config.env with GitHub environment variables.
# 5. Installs dependencies in a clean, deterministic way.
# 6. Runs the project's tests.

name: Run tests

on:
  workflow_dispatch:  # This trigger allows for manual execution of the workflow.

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the job.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Check out the repository code to the runner.

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Set up Node.js environment.
        with:
          node-version: 20  # Use Node.js version 20.

      - name: Create logs-config.env from GitHub environment variables
        run: |
          echo "LOG_MODE=${{vars.LOG_MODE}}" > logs-config.env
          echo "CONSOLE_COLORS=${{secrets.CONSOLE_COLORS}}" >> logs-config.env
          echo "CONSOLE_GROUPING=${{secrets.CONSOLE_GROUPING}}" >> logs-config.env

      - name: Display the content of logs-config.env
        run: cat logs-config.env  # Output the contents of the logs-config.env file to verify.

      - name: Cache Node.js modules
        uses: actions/cache@v3  # Cache dependencies to speed up future workflow runs.
        with:
          path: |
            ~/.npm/_cacache
            ~/.npm/_locks
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  # Cache key based on OS and lock file.
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci  # Install project dependencies in a clean, deterministic manner.

      - name: Run tests
        run: npm test  # Run the tests.
